name: AsgardTribes
main: com.fivefourdee.asgardtribes.AsgardTribes
version: 1.2.1
author: 54D
depend: [Vault]
commands:
   tribe:
       description: Main command.
       usage: /tribe
   tribes:
       description: Alias.
       usage: /tribes